In [ ]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.13.0


Tensors are mainly multi dimensional vectors. 1D vector / array is a 1D Tensor. Matrices are 2D tensors.

## Initialization of Tensors

In [ ]:
x = tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
x = tf.constant(4,shape=(5,5),dtype=tf.int32)
print(x)

tf.Tensor(
[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]], shape=(5, 5), dtype=int32)


In [ ]:
x = tf.constant([[1,2,3],[4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
x = tf.constant([[1,2,3],[4,5,6]],shape=(3,2))
print(x)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [ ]:
x= tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
x = tf.zeros((3,5))
print(x)

tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(3, 5), dtype=float32)


In [ ]:
x = tf.ones((3,4))
print(x)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


In [ ]:
x = tf.random.uniform((2,3),minval = 0,maxval=1)
print(x)

tf.Tensor(
[[0.06881976 0.17504537 0.6205548 ]
 [0.8478     0.7599354  0.7487613 ]], shape=(2, 3), dtype=float32)


In [ ]:
x = tf.random.normal((2,3),mean=0,stddev=1)
print(x)

tf.Tensor(
[[ 0.38182393 -0.56163937  0.3257562 ]
 [ 0.20393048 -0.52278215  1.7703242 ]], shape=(2, 3), dtype=float32)


In [ ]:
x = tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [ ]:
x = tf.range(start=0,limit=10,delta=2)
print(x)

tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


In [ ]:
x = tf.cast(x,tf.float64)
print(x)

tf.Tensor([0. 2. 4. 6. 8.], shape=(5,), dtype=float64)


### Mathematical Operations

In [ ]:
a = tf.constant([1,2,3])
b = tf.constant([4,5,6])

In [ ]:
z = tf.add(a,b)
print(z)
# we can also we z = a+b => This is similar to tf.add(a,b)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


To add two tensors , they have to be in the same shape

In [ ]:
z = tf.subtract(a,b)
# z = a-b
print(z)

tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)


In [ ]:
z = tf.divide(a,b)
z = a/b
print(z)

tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [ ]:
z = tf.multiply(a,b)
z = a*b
print(z)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [ ]:
z = tf.tensordot(a,b,axes=1) # z = tf.reduce_sum(x*y,axes=0)
print(z)

tf.Tensor(32, shape=(), dtype=int32)


In [ ]:
z = a **2
print(z)

tf.Tensor([1 4 9], shape=(3,), dtype=int32)


In [ ]:
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))

z = tf.matmul(x,y)
print(z)

z = x@y
print(z)

tf.Tensor(
[[-0.959259    3.143611   -5.70916     2.9847906 ]
 [-3.0476818   1.3869656   0.37158373 -0.8153502 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[-0.959259    3.143611   -5.70916     2.9847906 ]
 [-3.0476818   1.3869656   0.37158373 -0.8153502 ]], shape=(2, 4), dtype=float32)


In [ ]:
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
print(x[:])
print(x[1:]) # if we left any field blank then it will print to the last or to the first
print(x[1:3]) # first index is included but the last index is excluded
print(x[::2]) # step is 2 , means it will skip 1 element
print(x[::-1]) # print in reverse order

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [ ]:
indices = tf.constant([0, 3])
x_indices = tf.gather(x, indices)
print(x_indices)

tf.Tensor([0 2], shape=(2,), dtype=int32)


In [ ]:
x = tf.constant([[1,2],[3,4],[5,6]])
print(x[0])

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [ ]:
print(x[0,:1])
print(x[0,0])
# Both of them have the differnet shape

tf.Tensor([1], shape=(1,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
print(x[0:2,:])

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


### Reshaping

In [ ]:
x = tf.range(9)

x = tf.reshape(x, (3, 3))
print(x)
x = tf.transpose(x, perm=[1, 0])
print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
